from urllib import request
from bs4 import BeautifulSoup

#Lecture du fichier texte contenant la clé

api_key = "eyJ4NXQiOiJZV0kxTTJZNE1qWTNOemsyTkRZeU5XTTRPV014TXpjek1UVmhNbU14T1RSa09ETXlOVEE0Tnc9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJNQUtITE9VRkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6Ik1BS0hMT1VGIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IlVubGltaXRlZCIsIm5hbWUiOiJEZWZhdWx0QXBwbGljYXRpb24iLCJpZCI6OTMwNCwidXVpZCI6IjY2NDdiZjM3LWJkZGEtNGViOC1iMDczLWEzMzdlMGE2ZjZhMSJ9LCJpc3MiOiJodHRwczpcL1wvcG9ydGFpbC1hcGkubWV0ZW9mcmFuY2UuZnI6NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiNTBQZXJNaW4iOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6InNlYyJ9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJBUk9NRSIsImNvbnRleHQiOiJcL3B1YmxpY1wvYXJvbWVcLzEuMCIsInB1Ymxpc2hlciI6ImFkbWluX21mIiwidmVyc2lvbiI6IjEuMCIsInN1YnNjcmlwdGlvblRpZXIiOiI1MFBlck1pbiJ9XSwiZXhwIjoxNzA4MTI2NTUyLCJ0b2tlbl90eXBlIjoiYXBpS2V5IiwiaWF0IjoxNzA4MDkwNTUyLCJqdGkiOiJjODA5MDhhYy02MTQyLTQ5ODYtYWI5Ny01YTY1MmRiNGJlNzAifQ==.EdsKNudqZrj2e_sa3ARiJnL8Ayb0hdGTznpDn4FmNkGk5Wly2pCaNfMHHG3pWnAKTbyGMV3PIQkgMCWiACdihdPt95gUlxZKIH4bVPtLrBuS39tvVG7k9P-FwcrGY2pc1dOUxhK26Q1mDnMWp58H4E7fjy131Jb16ByRPn69xlQIU_w17kwI63gs2e7zJfqgjHmdDJW2V14nwFxd8jpYs99fUgUFKHgsBZp4u9Xi9I5AyDn1mvHYuane6PsIT4sl5JMMo2MqrbUA7EqfR9AIrX5Ddusdqz2tks6Zi71KR7L4u5z4xRjTmDc3yV4nWAet5SM_VMKHi-haJHy7Wx-guw=="
    
#Nom de la prévision recherchée
ID = "TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND"


#Ressource à laquelle on souhaite accéder 
ressource = "arpege/1.0/wms/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WMS/GetCapabilities?service=WMS"

#URL à interroger
url = f"https://public-api.meteofrance.fr/public/{ressource}&apikey={api_key}"

#On récupère la réponse de l'API et on la met en forme avec BeautifulSoup
response = request.urlopen(url)
soup = BeautifulSoup(response.read())
