# Current datetime
import requests
from requests.auth import HTTPBasicAuth
import requests
from datetime import datetime
import os




current_datetime = datetime.now()

# Extract the date part and hour
date_only = current_datetime.date()
heure = current_datetime.hour

# Determine forecast time based on current hour
if heure < 12:
    heure_prevision = "00"
else:
    heure_prevision = "12"

# Package name
nom_paquet = "IP1"

# Echeance
echeance = "000H024H"


# API key (use your own valid API key here)
apikey = "eyJ4NXQiOiJZV0kxTTJZNE1qWTNOemsyTkRZeU5XTTRPV014TXpjek1UVmhNbU14T1RSa09ETXlOVEE0Tnc9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJNQUtITE9VRkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6Ik1BS0hMT1VGIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IjEwUGVyTWluIiwibmFtZSI6IlJlY3VwZXJhdGlvbl9kb25uZWVzX21ldGVvX2ZyYW5jZSIsImlkIjo5MzEzLCJ1dWlkIjoiMWZhY2E0NWYtYmU3ZS00NDA1LWE2MjUtOTJkNzI1MTkxMGQ2In0sImlzcyI6Imh0dHBzOlwvXC9wb3J0YWlsLWFwaS5tZXRlb2ZyYW5jZS5mcjo0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyI1MFBlck1pbiI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0Ijoic2VjIn0sIjM1MFJlcVBhck1pbiI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0Ijoic2VjIn0sIlVubGltaXRlZCI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwicGVybWl0dGVkUmVmZXJlciI6IiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IkFST01FIiwiY29udGV4dCI6IlwvcHVibGljXC9hcm9tZVwvMS4wIiwicHVibGlzaGVyIjoiYWRtaW5fbWYiLCJ2ZXJzaW9uIjoiMS4wIiwic3Vic2NyaXB0aW9uVGllciI6IjUwUGVyTWluIn0seyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IkFSUEVHRSIsImNvbnRleHQiOiJcL3B1YmxpY1wvYXJwZWdlXC8xLjAiLCJwdWJsaXNoZXIiOiJhZG1pbl9tZiIsInZlcnNpb24iOiIxLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiNTBQZXJNaW4ifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiUGFxdWV0QVJQRUdFIiwiY29udGV4dCI6IlwvcHJldmludW1cL0RQUGFxdWV0QVJQRUdFXC92MSIsInB1Ymxpc2hlciI6ImZyaXNib3VyZyIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiUGFxdWV0QVJPTUUtT00iLCJjb250ZXh0IjoiXC9wcmV2aW51bVwvRFBQYXF1ZXRBUk9NRS1PTVwvdjEiLCJwdWJsaXNoZXIiOiJmcmlzYm91cmciLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiMzUwUmVxUGFyTWluIn0seyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IlBhcXVldEFST01FIiwiY29udGV4dCI6IlwvcHJldmludW1cL0RQUGFxdWV0QVJPTUVcL3YxIiwicHVibGlzaGVyIjoiZnJpc2JvdXJnIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IjUwUGVyTWluIn1dLCJ0b2tlbl90eXBlIjoiYXBpS2V5IiwicGVybWl0dGVkSVAiOiIiLCJpYXQiOjE3MDgxODcxMDAsImp0aSI6IjNjODBhNTQ2LTdhYjItNDAxYy1hZmY1LWMwZjdlNWVmNDk3YiJ9.ByvNcLX8LOf-nPXcgjba-nw0XgukTv2jP1uL2JkIb7xiIfZEwWPQzfI2SM6ACaGIxg7dZQPth4Dp9Mt7ePdxEmQnqPsuY4PMafoDOy9t7llHHr5jAMNGqDlW5OeBvpVsgrhGm_4zxSLqgxLbK64rjSDQeJ7KfpQe0Sd9dBvoOoUBXB4Pt4wFVpIi43Y6y75J-IGlWzgllOBzaMvquNIKj3Aqi2v7atXRnvobvGUZ8BS-vSzAen8p0rbyQQR5wGJZuu63OYk84ju_da1bDE_lxJJcBtUXEpWFHMG9bA1yg9fAangeI0169NiSOF3lpk9Ujt3euzu9aeU0-S67hTh37w=="

# Date for the forecast
date_string = date_only.strftime("%Y-%m-%d")

# URL for downloading Meteo France forecast data
URL = "https://public-api.meteofrance.fr/previnum/DPPaquetARPEGE/v1/models/ARPEGE/grids/0.25/packages/"+nom_paquet+"/productARP?referencetime="+date_string+"T"+"00"+"%3A00%3A00Z&time="+echeance+"&format=grib2"

response = requests.get(URL, headers={"apikey": apikey})

# Path to save the downloaded file
nom_fichier = nom_fichier = "donnees_meteo_france/"+date_string+ ".grib"


if response.ok:
    # Save the content to a .grib2 file
    with open(nom_fichier, 'wb') as file:
        file.write(response.content)
    print("GRIB file saved successfully.")
else:
    print("Failed to fetch data.")

